version: '3.7'
services:
  nest:
    image: meetmeet-container-registry.kr.ncr.ntruss.com/nest:latest
    container_name: nest
    restart: always
    ports:
      - 3000:3000
    volumes:
      - .env:/var/app/.env
      - ./meetmeet-firebase.json:/var/app/meetmeet-firebase.json
      - ./logs:/var/app/logs
    command: npm run start:dev
