version: "3.7"
services:
  nest:
    image: nest:latest
    container_name: nest
    restart: always
    ports:
      - 3000:3000
    volumes:
      - .env:/var/app/.env
    command: npm run start:dev
