package com.teameetmeet.meetmeet.service

const val INTENT_REQUEST_ID_ALARM_UPDATE = -1
const val INTENT_REQUEST_ID_EVENT_NOTIFICATION = -2
const val INTENT_REQUEST_ID_FOLLOW_NOTIFICATION = -3
const val INTENT_REQUEST_ID_EVENT_INVITATION_NOTIFICATION = -4